version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.4
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login --region ap-southeast-2 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=511491950469.dkr.ecr.us-east-1.amazonaws.com/excel_export_aws
    - IMAGE_TAG=1.0
  build:
    commands:
    - echo generating app key
    - php artisan key:generate
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG 