version: '3.5'

services:
  app:
    build:
      context: '.'
    container_name: app
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    networks:
      - backend-network

  db:
    ports:
      - 3306:3306
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=csv_export
      - MYSQL_USER=xs800543_kuizy
      - MYSQL_PASSWORD=12345678
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  store: